### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by lys-6** [MakeLikePaperrr/Fracture-Preprocessing-Code#1]
Since I am a beginner and have run your code I have some questions I would like to ask you.
There are 4 columns in the "real_txt" file, the first column is the x coordinate of the node, the second column is the y coordinate, I want to know the meaning of the third and fourth columns.
I'd appreciate it if you could tell me.
Wish you a happy life!
[新建 DOCX 文档.pdf](https://github.com/user-attachments/files/16782071/DOCX.pdf)

**Comment by MakeLikePaperrr** [comment]
Hi, is the attached file relevant to your question btw, if so, could you explain why? I did not open it since I don't really trust the name of the file haha. 

But to answer your question: the files that you can find in the Datasets/Whitby and Brejoes folders are list of fracture segments. A fracture segments consists of two nodes, so the first two columns are the (x,y)-coordinates of the first node of the segment, the third and fourth column are the (x,y)-coordinates of the second node. See picture below:
![image](https://github.com/user-attachments/assets/f5f0f8e4-475f-410d-9c82-d4380e99e4a3)

I hope this helps :)! And let me know if you find any other issues.

**Comment by lys-6** [comment]
I am honored to receive your reply, which is very helpful for a beginner like me!


I have another question. I don't seem to find any parameter related to the width of the crack in my code. Could you please tell me how the width of the randomly generated crack is determined?
I look forward to your reply and thank you very much.



---Original---
From: "Stephan de ***@***.***&gt;
Date: Wed, Aug 28, 2024 20:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MakeLikePaperrr/Fracture-Preprocessing-Code] consult (Issue #1)




 
Hi, is the attached file relevant to your question btw, if so, could you explain why? I did not open it since I don't really trust the name of the file haha.
 
But to answer your question: the files that you can find in the Datasets/Whitby and Brejoes folders are list of fracture segments. A fracture segments consists of two nodes, so the first two columns are the (x,y)-coordinates of the first node of the segment, the third and fourth column are the (x,y)-coordinates of the second node. See picture below:
 image.png (view on web)
 
I hope this helps :)! And let me know if you find any other issues.

**Comment by MakeLikePaperrr** [comment]
The width of the fracture is usually called 'aperture' (in the literature but also in this code). There are different ways you could populate the aperture, either randomly, constant, based on the length of the fracture, or based on the expected in-situ stresses (fractures oriented along the largest principal stress are often much more open than fractures that oriented perpendicular to the largest principal stress). Please also see the paper attached to this repo, it is explained in great detail there :)! Hope this helps :)!
